//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspnetMvcDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات الحساب.
        /// </summary>
        public static string Account_settings {
            get {
                return ResourceManager.GetString("Account settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الإضافات (ل/م3) .
        /// </summary>
        public static string Addtion_Amount {
            get {
                return ResourceManager.GetString("Addtion Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الإضافات .
        /// </summary>
        public static string Addtion_Type {
            get {
                return ResourceManager.GetString("Addtion Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق .
        /// </summary>
        public static string Attached {
            get {
                return ResourceManager.GetString("Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتوماتيكي.
        /// </summary>
        public static string Atuomatic {
            get {
                return ResourceManager.GetString("Atuomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل الإنتاج اليومي.
        /// </summary>
        public static string Average_Daily_Production {
            get {
                return ResourceManager.GetString("Average Daily Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات عينة البلوك.
        /// </summary>
        public static string Block_Sapmle_Infromation {
            get {
                return ResourceManager.GetString("Block Sapmle Infromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور كسر عينة خرسانة.
        /// </summary>
        public static string Break_Concrete_Sample {
            get {
                return ResourceManager.GetString("Break Concrete Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادات المعايرة .
        /// </summary>
        public static string Calibration_certificates {
            get {
                return ResourceManager.GetString("Calibration certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصدر الاسمنت.
        /// </summary>
        public static string Cement_Source {
            get {
                return ResourceManager.GetString("Cement Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الاسمنت .
        /// </summary>
        public static string Cement_Type {
            get {
                return ResourceManager.GetString("Cement Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الاسمنت (كجم).
        /// </summary>
        public static string Cement_Weight {
            get {
                return ResourceManager.GetString("Cement Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظافة .
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل .
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمدة .
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجاري.
        /// </summary>
        public static string Commercial_Register {
            get {
                return ResourceManager.GetString("Commercial Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPa رتبة العينة نيوتن (نيوتن / مم2).
        /// </summary>
        public static string Concrete_Rank {
            get {
                return ResourceManager.GetString("Concrete Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عينة الخرسانة.
        /// </summary>
        public static string Concrete_Sample {
            get {
                return ResourceManager.GetString("Concrete Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الخرسانة (مْ).
        /// </summary>
        public static string Concrete_Tempereture {
            get {
                return ResourceManager.GetString("Concrete Tempereture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام الخرسانة.
        /// </summary>
        public static string Concrete_Using {
            get {
                return ResourceManager.GetString("Concrete Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مصنع جديد.
        /// </summary>
        public static string Create_Factory {
            get {
                return ResourceManager.GetString("Create Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام عينة بلوك.
        /// </summary>
        public static string Deliver_Block {
            get {
                return ResourceManager.GetString("Deliver Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام عينة خرسانه .
        /// </summary>
        public static string Deliver_Concrete {
            get {
                return ResourceManager.GetString("Deliver Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايعاد (الطول * العرض * الارتفاع ) ملم.
        /// </summary>
        public static string Dim {
            get {
                return ResourceManager.GetString("Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الهبوط (مم).
        /// </summary>
        public static string Down_Amount {
            get {
                return ResourceManager.GetString("Down Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني للمصنع .
        /// </summary>
        public static string Factory_Email {
            get {
                return ResourceManager.GetString("Factory Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم  فاكس المصنع .
        /// </summary>
        public static string Factory_Fax {
            get {
                return ResourceManager.GetString("Factory Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المصنع.
        /// </summary>
        public static string Factory_Info {
            get {
                return ResourceManager.GetString("Factory Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المصنع.
        /// </summary>
        public static string Factory_Name {
            get {
                return ResourceManager.GetString("Factory Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف المصنع .
        /// </summary>
        public static string Factory_Phone_Number {
            get {
                return ResourceManager.GetString("Factory Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المصنع.
        /// </summary>
        public static string Factory_Status {
            get {
                return ResourceManager.GetString("Factory Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التزام العاملين بالمصنع بلبس الكمامات.
        /// </summary>
        public static string Factory_workers_commitment_to_wear_masks {
            get {
                return ResourceManager.GetString("Factory workers commitment to wear masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المصنع.
        /// </summary>
        public static string Factroy_Location {
            get {
                return ResourceManager.GetString("Factroy Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المصنع.
        /// </summary>
        public static string Factroy_Type {
            get {
                return ResourceManager.GetString("Factroy Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم زيارة المصنع.
        /// </summary>
        public static string Factroy_Visit_Number {
            get {
                return ResourceManager.GetString("Factroy Visit Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الملف .
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات عامة .
        /// </summary>
        public static string Global_Information {
            get {
                return ResourceManager.GetString("Global Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترخيص الصناعي.
        /// </summary>
        public static string Industrial_license {
            get {
                return ResourceManager.GetString("Industrial license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أساسيات .
        /// </summary>
        public static string Infastructure {
            get {
                return ResourceManager.GetString("Infastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة .
        /// </summary>
        public static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادات الأيزو .
        /// </summary>
        public static string ISO_certificates {
            get {
                return ResourceManager.GetString("ISO certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود مختبر .
        /// </summary>
        public static string Laboratory_Exist {
            get {
                return ResourceManager.GetString("Laboratory Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواجد مهندس المختبر.
        /// </summary>
        public static string Laboratroy_Engineer_Exist {
            get {
                return ResourceManager.GetString("Laboratroy Engineer Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خط الطول .
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login_to_Your_Account {
            get {
                return ResourceManager.GetString("Login to Your Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لمدير المصنع .
        /// </summary>
        public static string Manager__Email {
            get {
                return ResourceManager.GetString("Manager  Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مدير المصنع.
        /// </summary>
        public static string Manager__Name {
            get {
                return ResourceManager.GetString("Manager  Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال مدير المصنع .
        /// </summary>
        public static string Manager__PhoneNumber {
            get {
                return ResourceManager.GetString("Manager  PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي وسنوات الخبرة.
        /// </summary>
        public static string Manager_Experience__years_ {
            get {
                return ResourceManager.GetString("Manager Experience (years)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يدوي.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخلطة التصميمية.
        /// </summary>
        public static string Mix_Design {
            get {
                return ResourceManager.GetString("Mix Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الخلاطة .
        /// </summary>
        public static string Mixer_Number {
            get {
                return ResourceManager.GetString("Mixer Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الانتقال.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترخيص البلدية .
        /// </summary>
        public static string Municipality_license {
            get {
                return ResourceManager.GetString("Municipality license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مرفق .
        /// </summary>
        public static string Not_Attached {
            get {
                return ResourceManager.GetString("Not Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات .
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشعارات.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بواسطة نقرة لتنقية المعلومات .
        /// </summary>
        public static string Nqraa_Solutions {
            get {
                return ResourceManager.GetString("Nqraa Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لصاحب المصنع .
        /// </summary>
        public static string Owner_Email {
            get {
                return ResourceManager.GetString("Owner Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المالك والمديرين.
        /// </summary>
        public static string Owner_Info {
            get {
                return ResourceManager.GetString("Owner Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم صاحب المصنع .
        /// </summary>
        public static string Owner_Name {
            get {
                return ResourceManager.GetString("Owner Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال صاحب المصنع.
        /// </summary>
        public static string Owner_Phone_Number {
            get {
                return ResourceManager.GetString("Owner Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامة الجودة .
        /// </summary>
        public static string performance_sign {
            get {
                return ResourceManager.GetString("performance sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Pervious {
            get {
                return ResourceManager.GetString("Pervious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق بريد المصنع .
        /// </summary>
        public static string Post_Code {
            get {
                return ResourceManager.GetString("Post Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضر عينة بلوك .
        /// </summary>
        public static string Prepare_Block {
            get {
                return ResourceManager.GetString("Prepare Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضير عينة خرسانة.
        /// </summary>
        public static string Prepare_Concrete {
            get {
                return ResourceManager.GetString("Prepare Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضيرات العينات .
        /// </summary>
        public static string Prepare_Samples {
            get {
                return ResourceManager.GetString("Prepare Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطاقة الإنتاجية.
        /// </summary>
        public static string Produce_Power {
            get {
                return ResourceManager.GetString("Produce Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة الجودة.
        /// </summary>
        public static string Quality_Control {
            get {
                return ResourceManager.GetString("Quality Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جودة التحكم في الغبار المتطاير من الخلاطة.
        /// </summary>
        public static string Quality_control_of_flying_dust_from_the_mixer {
            get {
                return ResourceManager.GetString("Quality control of flying dust from the mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لمهندس الجودة.
        /// </summary>
        public static string Quality_Engineer__Email {
            get {
                return ResourceManager.GetString("Quality Engineer  Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال مهندس الجودة .
        /// </summary>
        public static string Quality_Engineer__PhoneNumber {
            get {
                return ResourceManager.GetString("Quality Engineer  PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي وسنوات الخبرة .
        /// </summary>
        public static string Quality_Engineer_Experience__years_ {
            get {
                return ResourceManager.GetString("Quality Engineer Experience (years)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مهندس الجودة .
        /// </summary>
        public static string Quality_Engineer_Name {
            get {
                return ResourceManager.GetString("Quality Engineer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جودة نظافة الموقع .
        /// </summary>
        public static string Quality_of_Factory_Cleaning {
            get {
                return ResourceManager.GetString("Quality of Factory Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة جودة مصانع الخرسانة والبلوك.
        /// </summary>
        public static string Quanlity_Control_System_for_Concrete {
            get {
                return ResourceManager.GetString("Quanlity Control System for Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التقرير.
        /// </summary>
        public static string Report_Date {
            get {
                return ResourceManager.GetString("Report Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التقرير .
        /// </summary>
        public static string Report_Number {
            get {
                return ResourceManager.GetString("Report Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع البلوك.
        /// </summary>
        public static string Report_Visit_Block_Factory {
            get {
                return ResourceManager.GetString("Report Visit Block Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع خرسانة.
        /// </summary>
        public static string Report_Visit_Concrete_Factory {
            get {
                return ResourceManager.GetString("Report Visit Concrete Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسقف .
        /// </summary>
        public static string Roofs {
            get {
                return ResourceManager.GetString("Roofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الركام 4/3 (كجم).
        /// </summary>
        public static string Rubble_3_4 {
            get {
                return ResourceManager.GetString("Rubble 3/4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الركام 8/3 (كجم).
        /// </summary>
        public static string Rubble_3_8 {
            get {
                return ResourceManager.GetString("Rubble 3/8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العينة .
        /// </summary>
        public static string Sample_Number {
            get {
                return ResourceManager.GetString("Sample Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت العينة.
        /// </summary>
        public static string Sample_Time {
            get {
                return ResourceManager.GetString("Sample Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع المصنع.
        /// </summary>
        public static string Select_Factroy_Type {
            get {
                return ResourceManager.GetString("Select Factroy Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتوماتيكي جزئي.
        /// </summary>
        public static string Semi_Atuomatic {
            get {
                return ResourceManager.GetString("Semi Atuomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكل.
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رؤية كل الإشعارات.
        /// </summary>
        public static string Show_all_notifications {
            get {
                return ResourceManager.GetString("Show all notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل .
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل كمصنع جديد.
        /// </summary>
        public static string Signup_as_new_Factory {
            get {
                return ResourceManager.GetString("Signup as new Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رش الركام في فصل الصيف.
        /// </summary>
        public static string Spray_debris_in_the_summer {
            get {
                return ResourceManager.GetString("Spray debris in the summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الأولى.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الثانية.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الثالثة.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الرابعة.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخلطات التصميمية المستخدمة.
        /// </summary>
        public static string The_design_mixture_used {
            get {
                return ResourceManager.GetString("The design mixture used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود ملدنات في سيارة نقل الخرسانة.
        /// </summary>
        public static string The_presence_of_plasticizers_in_the_concrete_transport_vehicle {
            get {
                return ResourceManager.GetString("The presence of plasticizers in the concrete transport vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواجد مهندس المختبر.
        /// </summary>
        public static string The_presence_of_the_laboratory_engineer {
            get {
                return ResourceManager.GetString("The presence of the laboratory engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الخلاطات بالمصنع .
        /// </summary>
        public static string Total_Mixers_Number {
            get {
                return ResourceManager.GetString("Total Mixers Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الشاحنات .
        /// </summary>
        public static string Total_Truckers_Number {
            get {
                return ResourceManager.GetString("Total Truckers Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشاحنة .
        /// </summary>
        public static string Trucker_Number {
            get {
                return ResourceManager.GetString("Trucker Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرفاق.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الزيارة.
        /// </summary>
        public static string Visit_Date {
            get {
                return ResourceManager.GetString("Visit Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الزيارة.
        /// </summary>
        public static string Visit_Location {
            get {
                return ResourceManager.GetString("Visit Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الزيارة.
        /// </summary>
        public static string Visit_Reports {
            get {
                return ResourceManager.GetString("Visit Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع بلوك.
        /// </summary>
        public static string Visting__Block_Factroy_Report {
            get {
                return ResourceManager.GetString("Visting  Block Factroy Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمل المغسول (كجم) .
        /// </summary>
        public static string Washed_Sand {
            get {
                return ResourceManager.GetString("Washed Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الماء (مْ) .
        /// </summary>
        public static string Water_Tempreture {
            get {
                return ResourceManager.GetString("Water Tempreture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الماء (كجم) .
        /// </summary>
        public static string Water_Weight {
            get {
                return ResourceManager.GetString("Water Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الجو  (مْ).
        /// </summary>
        public static string Weather_Tempreture {
            get {
                return ResourceManager.GetString("Weather Tempreture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمل الأبيض (كجم) .
        /// </summary>
        public static string White_Sand {
            get {
                return ResourceManager.GetString("White Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم .
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
